# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OneDrive\我Python牛皮\密码学实验\5RSA\RSA.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 785)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mw = QtWidgets.QTextEdit(self.centralwidget)
        self.mw.setGeometry(QtCore.QRect(60, 290, 381, 51))
        self.mw.setObjectName("mw")
        self.mw2 = QtWidgets.QTextEdit(self.centralwidget)
        self.mw2.setGeometry(QtCore.QRect(60, 350, 381, 301))
        self.mw2.setObjectName("mw2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 300, 54, 12))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 360, 54, 12))
        self.label_3.setObjectName("label_3")
        self.sj = QtWidgets.QPushButton(self.centralwidget)
        self.sj.setGeometry(QtCore.QRect(60, 250, 91, 23))
        self.sj.setObjectName("sj")
        self.jm2 = QtWidgets.QPushButton(self.centralwidget)
        self.jm2.setGeometry(QtCore.QRect(350, 250, 75, 23))
        self.jm2.setObjectName("jm2")
        self.jmw = QtWidgets.QTextEdit(self.centralwidget)
        self.jmw.setGeometry(QtCore.QRect(60, 670, 381, 61))
        self.jmw.setObjectName("jmw")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 680, 41, 21))
        self.label_5.setObjectName("label_5")
        self.jm = QtWidgets.QPushButton(self.centralwidget)
        self.jm.setGeometry(QtCore.QRect(200, 250, 75, 23))
        self.jm.setObjectName("jm")
        self.P = QtWidgets.QTextEdit(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(60, 20, 141, 41))
        self.P.setObjectName("P")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 54, 12))
        self.label_4.setObjectName("label_4")
        self.Q = QtWidgets.QTextEdit(self.centralwidget)
        self.Q.setGeometry(QtCore.QRect(280, 20, 141, 41))
        self.Q.setObjectName("Q")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 30, 54, 12))
        self.label_6.setObjectName("label_6")
        self.N = QtWidgets.QTextEdit(self.centralwidget)
        self.N.setGeometry(QtCore.QRect(60, 70, 361, 41))
        self.N.setObjectName("N")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 130, 54, 12))
        self.label_8.setObjectName("label_8")
        self.e = QtWidgets.QTextEdit(self.centralwidget)
        self.e.setGeometry(QtCore.QRect(60, 120, 361, 41))
        self.e.setObjectName("e")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 180, 54, 12))
        self.label_9.setObjectName("label_9")
        self.d = QtWidgets.QTextEdit(self.centralwidget)
        self.d.setGeometry(QtCore.QRect(60, 170, 361, 41))
        self.d.setObjectName("d")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA"))
        self.label.setText(_translate("MainWindow", "明文"))
        self.label_3.setText(_translate("MainWindow", "密文"))
        self.sj.setText(_translate("MainWindow", "随机生成密钥"))
        self.jm2.setText(_translate("MainWindow", "解密"))
        self.label_5.setText(_translate("MainWindow", "解密文"))
        self.jm.setText(_translate("MainWindow", "加密"))
        self.label_4.setText(_translate("MainWindow", "P"))
        self.label_6.setText(_translate("MainWindow", "Q"))
        self.label_7.setText(_translate("MainWindow", "N"))
        self.label_8.setText(_translate("MainWindow", "公钥e"))
        self.label_9.setText(_translate("MainWindow", "私钥d"))
